

USE IBR_ALO_JOB 
GO


IF EXISTS (SELECT 1 FROM sys.objects where name = 'NOTIFICACION' and type = 'u') BEGIN
   DROP TABLE NOTIFICACION
END
GO

Create table NOTIFICACION
(ID_NOTIFICACION  INT          NOT NULL IDENTITY(1,1)
,TOKEN            VARCHAR(50) NOT NULL
,DESCRIPCION      VARCHAR(100) NOT NULL
,ESTADO           BIT          NOT NULL
,EJECUCION        VARCHAR(01)  NOT NULL
,FECHA_EJECUCION  DATETIME     NOT NULL
,SERVICIO         BIT          NOT NULL)

GO

ALTER TABLE NOTIFICACION ADD PRIMARY KEY NONCLUSTERED (ID_NOTIFICACION)
GO
CREATE CLUSTERED INDEX K_LLAVE ON NOTIFICACION(TOKEN)
GO

