

USE IBR_ALO_JOB 
GO


IF EXISTS (SELECT 1 FROM sys.objects where name = 'NOTIFICACION_LOG' and type = 'u') BEGIN
   DROP TABLE NOTIFICACION_LOG
END
GO

Create table NOTIFICACION_LOG
(ID_NOTIFICACION      INT NOT NULL
,ID                   INT IDENTITY
,FECHA_EJECUCION      DATETIME NOT NULL)

GO
ALTER TABLE NOTIFICACION_LOG ADD PRIMARY KEY NONCLUSTERED (ID)
GO
CREATE CLUSTERED INDEX K_ORDEN ON NOTIFICACION_LOG(ID_NOTIFICACION,ID,FECHA_EJECUCION)
GO
