

USE IBR_ALO_JOB 
GO


IF EXISTS (SELECT 1 FROM sys.objects where name = 'NOTIFICACION_HORA' and type = 'u') BEGIN
   DROP TABLE NOTIFICACION_HORA
END
GO

Create table NOTIFICACION_HORA
(ID                   INT IDENTITY
,ID_NOTIFICACION      INT      NOT NULL
,HORA                 SMALLINT NOT NULL
,MINUTO               SMALLINT NOT NULL
,FECHA_EJECUCION      DATETIME NOT NULL)

GO
ALTER TABLE NOTIFICACION_HORA ADD PRIMARY KEY NONCLUSTERED (ID)
GO
CREATE CLUSTERED INDEX K_ID_NOTIFICACION ON  NOTIFICACION_HORA(ID_NOTIFICACION)
GO


