

USE IBR_ALO_JOB 
GO


IF EXISTS (SELECT 1 FROM sys.objects where name = 'NOTIFICACION_DIA' and type = 'u') BEGIN
   DROP TABLE NOTIFICACION_DIA
END
GO

Create table NOTIFICACION_DIA
(ID			      INT IDENTITY
,ID_NOTIFICACION  INT NOT NULL
,LUNES            BIT NOT NULL
,MARTES           BIT NOT NULL
,MIERCOLES        BIT NOT NULL
,JUEVES           BIT NOT NULL
,VIERNES          BIT NOT NULL
,SABADO           BIT NOT NULL
,DOMINGO          BIT NOT NULL
)

GO
ALTER TABLE NOTIFICACION_DIA ADD PRIMARY KEY NONCLUSTERED (ID)
GO
CREATE CLUSTERED INDEX K_ID_NOTIFICACION  ON NOTIFICACION_DIA (ID_NOTIFICACION);
GO




