

USE IBR_ALO_JOB 
GO


IF EXISTS (SELECT 1 FROM sys.objects where name = 'VALORES' and type = 'u') BEGIN
   DROP TABLE VALORES
END
GO

Create table VALORES
(ID_VALORES      INT NOT NULL
,ID_NOTIFICACION INT NOT NULL
,URL			 VARCHAR (255) NOT NULL
,SP				 VARCHAR(255) NOT NULL
,SISTEMA		 VARCHAR(255) NOT NULL
,PARAMETROS		 VARCHAR(MAX) NOT NULL
,FILTROS		 VARCHAR(MAX) NOT NULL)

GO
ALTER TABLE VALORES ADD PRIMARY KEY NONCLUSTERED (ID_VALORES)
GO

